name: graduates
favicon: null
layout_spectrum: 0.5995940216816962
typography_spectrum: 0.5699040133040398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.47120417444966733
  lightness: 0.7378529123961926
  saturation: 0.3622125401161611
  rhythmicContrast: 0.630703839007765
purpose: []
